local Games = {
  [3956818381] = "https://raw.githubusercontent.com/AmeloxRUS/guiforninjalegend/refs/heads/main/guininjalegends", -- Ninja legends
  [74698489978941] = "https://raw.githubusercontent.com/AmeloxRUS/PlantsVsFishes/refs/heads/main/fishser", -- Plants Vs Fishes
  [9872472334] = "https://raw.githubusercontent.com/AmeloxRUS/evade-script/refs/heads/main/evade", -- Evade
  [100591810023752] = "https://raw.githubusercontent.com/AmeloxRUS/grab-battles/refs/heads/main/grabattles", -- Grab Battles
  [142823291] = "https://raw.githubusercontent.com/AmeloxRUS/mm2/refs/heads/main/mm2", -- mm2
  [13827198708] = "https://raw.githubusercontent.com/AmeloxRUS/pullasword/refs/heads/main/pullaswords", -- pull a sword (IN DISCORD OPEN SOURCE!)
  [16732694052] = "https://raw.githubusercontent.com/AmeloxRUS/fisch/refs/heads/main/fisch", -- fisch
  [121864768012064] = "https://raw.githubusercontent.com/AmeloxRUS/FishIt/refs/heads/main/fishit", -- fisch it
  [662417684] = "https://raw.githubusercontent.com/AmeloxRUS/luckblock/refs/heads/main/wqeqwe", -- LUCKY BLOCKS Battlegrounds
  [102871156420149] = "https://raw.githubusercontent.com/AmeloxRUS/svogoyda/refs/heads/main/svo", -- the lost front
  [95457676979352] = "https://raw.githubusercontent.com/AmeloxRUS/smashatower/refs/heads/main/smash", -- SMASH a Tower
  [131623223084840] = "https://raw.githubusercontent.com/AmeloxRUS/brainrotshit/refs/heads/main/www", -- Escape Tsunami For Brainrot I FIX IT!!!!
  [135094773390024] = "https://raw.githubusercontent.com/AmeloxRUS/brainrotikiiii/refs/heads/main/bbbb", -- Escape Police For Brainrots
  [89103233089742] = "https://raw.githubusercontent.com/AmeloxRUS/trainbrainrot/refs/heads/main/www", -- Chase Train for Brainrots
  [134763881293027] = "https://raw.githubusercontent.com/AmeloxRUS/Steal-From-Brainrots/refs/heads/main/coldteamx" -- Steal From Brainrots
}

return Games
